version: '3.9'

services:
  app:
    build: .
    container_name: little_florist
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/vendor

    command: >
      sh -c "
        chown -R www-data:www-data storage bootstrap/cache &&
        chmod -R 775 storage bootstrap/cache &&

        [ -f .env ] || cp .env.example .env &&

        sed -i 's|DB_HOST=.*|DB_HOST=db|' .env &&
        sed -i 's|DB_DATABASE=.*|DB_DATABASE=little_florist|' .env &&
        sed -i 's|DB_USERNAME=.*|DB_USERNAME=laravel|' .env &&
        sed -i 's|DB_PASSWORD=.*|DB_PASSWORD=root|' .env &&
        sed -i 's|APP_URL=.*|APP_URL=https://little-florist.alanpratama.site|' .env &&
        sed -i 's|ASSET_URL=.*|ASSET_URL=https://little-florist.alanpratama.site|' .env &&

        echo 'Waiting for MySQL...'
        until nc -z db 3306; do
            sleep 2
        done

        echo 'MySQL is ready!'

        composer install &&
        php artisan key:generate --force &&

        php artisan migrate --force || true &&
        php artisan db:seed ProductSeeder || true &&
        php artisan db:seed UserSeeder || true &&

        php artisan storage:link || true &&

        php artisan config:clear &&
        php artisan cache:clear &&
        php artisan route:clear &&
        php artisan view:clear &&
        php-fpm
      "
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: little_florist_nginx
    restart: unless-stopped
    ports:
    - "8081:80"
    volumes:
    - .:/var/www
    - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
    - app


  db:
    image: mysql:8.0
    container_name: little_florist_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: little_florist
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
