version: '3.9'

services:
  app:
    build: .
    container_name: little_florist
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: little_florist_nginx
    restart: unless-stopped
    ports:
    - "8080:80"
    volumes:
    - .:/var/www
    - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
    - app


  db:
    image: mysql:8.0
    container_name: little_florist_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: little-florist
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
